### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'config/contrast_dct.json'

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/ivado-medical-imaging#164]
When importing ivadomed (782156156419c86505628e2cebf41c50cbb4e372) from the Terminal, everything goes well. However, when trying to import from IDE Pycharm, I get the following error:

```python
/Users/julien/code/sct/python/envs/venv_sct/bin/python "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 56211 --file /Users/julien/code/sct/scripts/sct_deepseg.py -i t2/t2.nii.gz -m /Users/julien/code/ivado-medical-imaging/testing_data/model_unet_test.pt
pydev debugger: process 48942 is connecting

Connected to pydev debugger (build 191.7479.30)
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/julien/code/sct/scripts/sct_deepseg.py", line 12, in <module>
    from ivadomed.utils import segment_volume
  File "/Users/julien/code/ivado-medical-imaging/ivadomed/utils.py", line 14, in <module>
    from ivadomed import loader as ivadomed_loader
  File "/Users/julien/code/ivado-medical-imaging/ivadomed/loader.py", line 21, in <module>
    with open("config/contrast_dct.json", "r") as fhandle:
FileNotFoundError: [Errno 2] No such file or directory: 'config/contrast_dct.json'
```

**Comment by jcohenadad** [comment]
Insight: when importing outside of ivadomed's directory, the error comes up (even from the Terminal). So there is probably a hard-coded path somewhere...

**Comment by jcohenadad** [comment]
yup! here's the problem:
https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/loader.py#L21
