### ISSUE TITLE
Problem of linking files to ivadomed package

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/ivado-medical-imaging#196]
When [installing ivadomed via pip](https://github.com/neuropoly/spinalcordtoolbox/pull/2639/commits/4c4a5f6d8a0866614809c64b24d1f882a2501910), the following error message appears while trying to import `ivadomed.utils` package:

```python
>>> import ivadomed.utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/ivadomed/utils.py", line 17, in <module>
    from ivadomed import loader as imed_loader
  File "/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/ivadomed/loader.py", line 19, in <module>
    with open(os.path.join(__path__[0], "../config/contrast_dct.json"), "r") as fhandle:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/ivadomed/../config/contrast_dct.json'
```

This is due to the way files that are part of the ivadomed are accessed: when using ivadomed locally from the git installation, it works, however when installing it via pip, some of the required files are missing.

**Comment by jcohenadad** [comment]
Those config files should be packaged as described [here](https://python-packaging.readthedocs.io/en/latest/non-code-files.html).
